# Generated by Django 5.0.7 on 2024-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_remove_item_created_remove_item_name_item_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('favourites', models.ManyToManyField(related_name='liked_by', to='books.item')),
            ],
        ),
    ]
